[project]
name = "cinemabot"
version = "1.0.0"
description = "(Not Written)"

dependencies = [
    "aiogram",
    "uwsgi",
    "flask",
    "requests",
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >= 3.2"]
